version: '3'

services:
  backend:
    build:
      context: ./pdfchat
    container_name: chatui_backend
    ports:
      - 8503:8503

  frontend:
    build:
      context: ./chatbot_ui
    container_name: chatui_frontend
    ports:
      - 3001:3001